Repository DeveloperAcademy-POSTECH/MacC-Dime-Vincent, pull requests merged in 2022-10, with the labels that each got.

#5 💄 ItemTappedView를 스크롤할 수 있고 스크롤화면 하단에 찜하기와 거래하기 버튼이 고정되었습니다.
  Vincent.xcodeproj/project.pbxproj
  Vincent/Screens/ItemTapped/ItemTappedViewController.swift
Labels: 루키, UI

#9 :lipstick:/3-CategoryView의 기본 UI를 그렸습니다.
  Vincent.xcodeproj/project.pbxproj
  Vincent/Global/Resource/Assets.xcassets/wallpaperNone.imageset/Contents.json
  Vincent/Global/Resource/Assets.xcassets/wallpaperNone.imageset/wallpaperNone.jpeg
  Vincent/Screens/Category/CategoryViewController.swift
Labels: 켄, UI

#10 💄Item 상세정보를 볼 수 있는 UI 구현이 완료되었습니다.
  Vincent.xcodeproj/project.pbxproj
  Vincent/Global/Extensions/UITextView+Extension.swift
  Vincent/Global/Resource/Assets.xcassets/Ken.imageset/Contents.json
  Vincent/Global/Resource/Assets.xcassets/Ken.imageset/Ken.jpg
  Vincent/Global/Resource/Assets.xcassets/i1.imageset/Contents.json
  Vincent/Global/Resource/Assets.xcassets/i1.imageset/IMG_8032.jpg
  Vincent/Global/Resource/Assets.xcassets/i2.imageset/Contents.json
  Vincent/Global/Resource/Assets.xcassets/i2.imageset/IMG_8033.jpg
  Vincent/Global/Resource/Assets.xcassets/i3.imageset/Contents.json
  Vincent/Global/Resource/Assets.xcassets/i3.imageset/IMG_8034.jpg
  Vincent/Global/Resource/Assets.xcassets/i4.imageset/Contents.json
  Vincent/Global/Resource/Assets.xcassets/i4.imageset/IMG_8035.jpg
  Vincent/Screens/ItemTapped/ItemTappedViewController.swift
Labels: 루키, UI

#17 💄 Message 채팅방 리스트와 채팅방 화면을 구성하였습니다.
  Vincent.xcodeproj/project.pbxproj
  Vincent.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Vincent/Global/Base/BaseViewController.swift
  Vincent/Global/Extensions/UICollectionView+Extension.swift
  Vincent/Global/Extensions/UILabel+Extension.swift
  Vincent/Global/Literal/ImageLiteral.swift
  Vincent/Global/Supports/Info.plist
  Vincent/Global/UIComponent/BackButton.swift
  Vincent/Models/Message/Channel.swift
  Vincent/Models/Message/ImageMediaItem.swift
  Vincent/Models/Message/Message.swift
  Vincent/Models/Message/Mocks.swift
  Vincent/Models/Message/Sender.swift
  Vincent/Screens/Message/Cell/MessageTableViewCell.swift
  Vincent/Screens/Message/MessageViewController.swift
  Vincent/Screens/MessageRoom/MessageRoomViewController.swift
  Vincent/Screens/MessageRoom/UIComponent/GoodInfoView.swift
Labels: 코비, UI

#19 💄 유저가 탭하여 신고를 할 수 있는 ItemTappedReportView의 Fundamental UI가 구현되었습니다.
  Vincent.xcodeproj/project.pbxproj
  Vincent/Screens/ItemTapped/ItemTappedViewController.swift
  Vincent/Screens/ItemTapped/ReportViewController.swift
Labels: 루키, UI

#13 💄 ProfileTappedView의 Fundamental UI가 완성되었습니다.
  Vincent.xcodeproj/project.pbxproj
  Vincent/Global/Literal/ImageLiteral.swift
  Vincent/Screens/ProfileTapped/ProfileEnumeration.swift
  Vincent/Screens/ProfileTapped/ProfileTableViewCell.swift
  Vincent/Screens/ProfileTapped/ProfileTappedViewController.swift
Labels: 루키, UI

#21 💄유저가 등록한 아이템들을 한 눈에 보는 창을 구현하였습니다.
  Vincent.xcodeproj/project.pbxproj
  Vincent/Global/Resource/Assets.xcassets/BeerKen.imageset/3BCD5BD8-75BB-4522-B6A7-5C7AAA20C868_1_105_c.jpeg
  Vincent/Global/Resource/Assets.xcassets/BeerKen.imageset/Contents.json
  Vincent/Global/Resource/Assets.xcassets/GiantRookie.imageset/C660BEA7-1B0E-4B97-9647-AEA00E464650_1_105_c.jpeg
  Vincent/Global/Resource/Assets.xcassets/GiantRookie.imageset/Contents.json
  Vincent/Global/Resource/Assets.xcassets/HackerKen.imageset/70BB7075-EF9F-45D0-AF83-5D289A4D078B_1_105_c.jpeg
  Vincent/Global/Resource/Assets.xcassets/HackerKen.imageset/Contents.json
  Vincent/Global/Resource/Assets.xcassets/Hardy.imageset/51266879-E73D-464E-A855-41FF6605035D.heic
  Vincent/Global/Resource/Assets.xcassets/Hardy.imageset/Contents.json
  Vincent/Global/Resource/Assets.xcassets/KidKen.imageset/27997FC4-E95E-4F5A-A699-ED8A2344F88A_1_105_c.jpeg
  Vincent/Global/Resource/Assets.xcassets/KidKen.imageset/Contents.json
  Vincent/Global/Resource/Assets.xcassets/WorkOutKen.imageset/34D36EE9-8230-41D2-A6AC-803602976657_1_105_c.jpeg
  Vincent/Global/Resource/Assets.xcassets/WorkOutKen.imageset/Contents.json
  Vincent/Screens/ArtItem/ArtItem.swift
  Vincent/Screens/ArtItem/ArtItemCategoryView.swift
  Vincent/Screens/ArtItem/ArtItemCategoryViewCell.swift
  Vincent/Screens/ArtItem/ArtItemCollectionView.swift
  Vincent/Screens/ArtItem/ArtItemCollectionViewCell.swift
  Vincent/Screens/ArtItem/ArtItemViewController.swift
Labels: 하디, UI

#26 :ambulance: PR Conflict해결
  Vincent/Screens/ItemTapped/ItemTappedViewController.swift
  Vincent/Screens/ItemTapped/ReportViewController.swift
Labels: bug, 루키

#29 Category view cherry pick fix
  Vincent.xcodeproj/project.pbxproj
  Vincent/Global/Resource/Assets.xcassets/BeerKen.imageset/3BCD5BD8-75BB-4522-B6A7-5C7AAA20C868_1_105_c.jpeg
  Vincent/Global/Resource/Assets.xcassets/BeerKen.imageset/Contents.json
  Vincent/Global/Resource/Assets.xcassets/GiantRookie.imageset/C660BEA7-1B0E-4B97-9647-AEA00E464650_1_105_c.jpeg
  Vincent/Global/Resource/Assets.xcassets/GiantRookie.imageset/Contents.json
  Vincent/Global/Resource/Assets.xcassets/HackerKen.imageset/70BB7075-EF9F-45D0-AF83-5D289A4D078B_1_105_c.jpeg
  Vincent/Global/Resource/Assets.xcassets/HackerKen.imageset/Contents.json
  Vincent/Global/Resource/Assets.xcassets/Hardy.imageset/51266879-E73D-464E-A855-41FF6605035D.heic
  Vincent/Global/Resource/Assets.xcassets/Hardy.imageset/Contents.json
  Vincent/Global/Resource/Assets.xcassets/KidKen.imageset/27997FC4-E95E-4F5A-A699-ED8A2344F88A_1_105_c.jpeg
  Vincent/Global/Resource/Assets.xcassets/KidKen.imageset/Contents.json
  Vincent/Global/Resource/Assets.xcassets/WorkOutKen.imageset/34D36EE9-8230-41D2-A6AC-803602976657_1_105_c.jpeg
  Vincent/Global/Resource/Assets.xcassets/WorkOutKen.imageset/Contents.json
  Vincent/Screens/ArtItem/ArtItem.swift
  Vincent/Screens/ArtItem/ArtItemCategoryView.swift
  Vincent/Screens/ArtItem/ArtItemCategoryViewCell.swift
  Vincent/Screens/ArtItem/ArtItemCollectionView.swift
  Vincent/Screens/ArtItem/ArtItemCollectionViewCell.swift
  Vincent/Screens/ArtItem/ArtItemViewController.swift
Labels: bug, 하디, UI

#40 🎨 ItemTappedView + ProfileTappedView UI 관련 수정 사항 반영
  Vincent.xcodeproj/project.pbxproj
  Vincent/Global/Literal/ImageLiteral.swift
  Vincent/Screens/ItemTapped/ItemTappedViewController.swift
  Vincent/Screens/ProfileTapped/ProfileTableViewCell.swift
  Vincent/Screens/ProfileTapped/ProfileTappedViewController.swift
Labels: 루키, UI, fix

#39 :sparkles: 파이어베이스 회원가입/로그인 추가
  Vincent.xcodeproj/project.pbxproj
  Vincent.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Vincent.xcodeproj/xcuserdata/coby.xcuserdatad/xcschemes/xcschememanagement.plist
  Vincent/Global/Extensions/Sequence+Extension.swift
  Vincent/Global/Supports/AppDelegate.swift
  Vincent/Global/Supports/GoogleService-Info.plist
  Vincent/Global/Supports/SceneDelegate.swift
  Vincent/Global/Utils/FirebaseManager.swift
  Vincent/Global/Utils/PushNotificationSender.swift
  Vincent/Models/User.swift
  Vincent/Screens/Login/LoginViewController.swift
  Vincent/Screens/SignUp/SignUpViewController.swift
Labels: enhancement, 코비
